# Generated by Django 5.2.3 on 2025-06-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('mechanic', 'Mechanic'), ('transport_manager', 'Transport Manager'), ('chief_officer', 'Chief Officer')], max_length=20),
        ),
    ]
