# Generated by Django 5.2.3 on 2025-07-16 02:04

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registrationrequest_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='license_class',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[core.models.validate_license_class]),
        ),
    ]
