# Generated by Django 5.2.3 on 2025-07-17 23:05

import django.core.validators
import django.db.models.deletion
import mechanics.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanic_id', models.CharField(default=mechanics.models.generate_mechanic_id, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='mechanic_profiles/')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on-leave', 'On Leave')], default='active', max_length=20)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='mechanics.mechanicprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicSupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mechanic_support_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mechanics.mechanicsupportrequest')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('issue_title', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('vehicle_number_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('unique_task_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.maintenancerequest')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanics.mechanicprofile')),
            ],
            options={
                'verbose_name': 'Mechanic Task',
                'verbose_name_plural': 'Mechanic Tasks',
            },
        ),
        migrations.CreateModel(
            name='RepairInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_unique_id', models.CharField(default=mechanics.models.generate_unique_task_id, editable=False, max_length=30, unique=True)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('issues', models.TextField(help_text='List the issues and approximate costs')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_of_service', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=50)),
                ('rejection_comment', models.TextField(blank=True)),
                ('action_timestamp', models.DateTimeField(auto_now_add=True)),
                ('mechanic_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='mechanics.mechanictask')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepairInvoicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='repair_invoices/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mechanics.repairinvoice')),
            ],
        ),
    ]
