# Generated by Django 5.2.3 on 2025-06-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='Comma-separated list of selected specializations.', max_length=255),
        ),
    ]
