# Generated by Django 5.2.3 on 2025-06-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0002_mechanicprofile_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='mechanics.specialization'),
        ),
    ]
