# Generated by Django 5.2.3 on 2025-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0003_specialization_remove_mechanicprofile_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='specializations',
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text="Comma-separated list of mechanic's areas of specialization", max_length=255),
        ),
    ]
