# Generated by Django 5.2.3 on 2025-06-29 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_maintenancerequest_mechanic'),
        ('mechanics', '0004_remove_mechanicprofile_specializations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='specialization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MechanicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('maintenance_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_task', to='drivers.maintenancerequest')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mechanics.mechanicprofile')),
            ],
        ),
    ]
