# Generated by Django 5.2.3 on 2025-06-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0007_auto_20250630_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanictask',
            name='unique_task_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
