# Generated by Django 5.2.3 on 2025-06-29 23:12

import mechanics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0008_alter_mechanictask_unique_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanictask',
            name='unique_task_id',
            field=models.CharField(default=mechanics.models.generate_unique_task_id, editable=False, max_length=8, unique=True),
        ),
    ]
