# Generated by Django 5.2.3 on 2025-07-07 06:03

import django.utils.timezone
import mechanics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0011_mechanicsupportrequest_mechanicsupportattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='join_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on-leave', 'On Leave')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='mechanic_id',
            field=models.CharField(default=mechanics.models.generate_mechanic_id, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mechanictask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
