# Generated by Django 5.2.3 on 2025-07-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0013_repairinvoice_action_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanictask',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mechanictask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
