# Generated by Django 5.2.3 on 2025-06-22 16:39

import django.db.models.deletion
import drivers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('defensive_driving', 'Defensive Driving'), ('first_aid', 'First Aid'), ('hazardous_materials', 'Hazardous Materials'), ('vehicle_inspection', 'Vehicle Inspection'), ('eco_driving', 'Eco Driving'), ('route_planning', 'Route Planning'), ('offroad_driving', 'Off-road Driving')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'A - Motorcycles'), ('B', 'B - Light Vehicles'), ('C', 'C - Medium Vehicles'), ('CE', 'CE - Heavy Commercial'), ('D', 'D - Passenger Service Vehicle'), ('E', 'E - Special Vehicles'), ('FG', 'FG - Industrial Equipment')], max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(default=drivers.models.generate_driver_id, max_length=6, unique=True)),
                ('license_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('department', models.CharField(default='Transport', max_length=100)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('current_vehicle', models.CharField(blank=True, max_length=100)),
                ('certifications', models.ManyToManyField(blank=True, to='drivers.certification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('license_classes', models.ManyToManyField(to='drivers.licenseclass')),
            ],
        ),
    ]
