# Generated by Django 5.2.3 on 2025-06-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_classes',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_number',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_class',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='current_vehicle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='supervisor',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
