# Generated by Django 5.2.3 on 2025-06-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_driverprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_profiles/'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='current_vehicle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='supervisor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
