# Generated by Django 5.2.3 on 2025-06-26 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverprofile_profile_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=15, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('last_update', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driverprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drivers.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='RequestIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost_estimate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='drivers.maintenancerequest')),
            ],
        ),
    ]
