# Generated by Django 5.2.3 on 2025-06-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_vehicle_maintenancerequest_requestissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
