# Generated by Django 5.2.3 on 2025-06-27 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_supportrequest'),
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='mechanic',
            field=models.ForeignKey(blank=True, help_text='Mechanic assigned to this maintenance request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='mechanics.mechanicprofile'),
        ),
    ]
