# Generated by Django 5.2.3 on 2025-07-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_vehicle_location_vehicle_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
